### Cleaning Entsoe data

In [47]:
import pandas as pd

In [48]:
load = pd.read_csv("/Users/saif/Desktop/ML_Load_Forecasting/data/Bronze/Entsoe_2020_2023.csv", index_col=0 , parse_dates= True)

load.index = pd.to_datetime(load.index, utc = True)
load.index = load.index.tz_localize(None)
load.columns = ["Load_MW"]
load = load.resample("1h").first()
load = load.iloc[1:]

In [49]:
load.head()

                      Load_MW
2020-01-01 00:00:00  43471.87
2020-01-01 01:00:00  42401.86
2020-01-01 02:00:00  41126.54
2020-01-01 03:00:00  40793.28
2020-01-01 04:00:00  40710.44

In [50]:
load.describe()

            Load_MW
count  35039.000000
mean   55672.268898
std     9829.387187
min    28407.440000
25%    47752.345000
50%    55607.140000
75%    63247.300000
max    81966.910000

In [51]:
load.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 35039 entries, 2020-01-01 00:00:00 to 2023-12-30 22:00:00
Freq: h
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Load_MW  35039 non-null  float64
dtypes: float64(1)
memory usage: 547.5 KB

In [52]:
load.corr()

         Load_MW
Load_MW      1.0

In [53]:
full_range = pd.date_range(
    start="2020-01-01 00:00:00",
    end="2023-12-31 23:00:00", 
    freq= "h"
)

In [54]:
missing = full_range.difference(load.index)

In [55]:
print(missing)
print(len(missing))

DatetimeIndex(['2023-12-30 23:00:00', '2023-12-31 00:00:00',
               '2023-12-31 01:00:00', '2023-12-31 02:00:00',
               '2023-12-31 03:00:00', '2023-12-31 04:00:00',
               '2023-12-31 05:00:00', '2023-12-31 06:00:00',
               '2023-12-31 07:00:00', '2023-12-31 08:00:00',
               '2023-12-31 09:00:00', '2023-12-31 10:00:00',
               '2023-12-31 11:00:00', '2023-12-31 12:00:00',
               '2023-12-31 13:00:00', '2023-12-31 14:00:00',
               '2023-12-31 15:00:00', '2023-12-31 16:00:00',
               '2023-12-31 17:00:00', '2023-12-31 18:00:00',
               '2023-12-31 19:00:00', '2023-12-31 20:00:00',
               '2023-12-31 21:00:00', '2023-12-31 22:00:00',
               '2023-12-31 23:00:00'],
              dtype='datetime64[us]', freq='h')
25

In [56]:
load = load.reindex(full_range)
load.tail()

                     Load_MW
2023-12-31 19:00:00      NaN
2023-12-31 20:00:00      NaN
2023-12-31 21:00:00      NaN
2023-12-31 22:00:00      NaN
2023-12-31 23:00:00      NaN

In [57]:
load = load.interpolate()
load.tail()

                      Load_MW
2023-12-31 19:00:00  42673.44
2023-12-31 20:00:00  42673.44
2023-12-31 21:00:00  42673.44
2023-12-31 22:00:00  42673.44
2023-12-31 23:00:00  42673.44

In [58]:
print(load.isna().sum())

Load_MW    0
dtype: int64

In [59]:
print(load.shape)

(35064, 1)

### Cleaning Weather data

In [ ]:
weather = pd.read_csv("/Users/saif/Desktop/ML_Load_Forecasting/data/Bronze/weather_2020_2023.csv", index_col=0, parse_dates=True)

weather.head()

                     temperature_2m  wind_speed_10m  shortwave_radiation
time
2020-01-01 00:00:00             1.5            11.4                  0.0
2020-01-01 01:00:00             2.0            10.3                  0.0
2020-01-01 02:00:00             1.8            11.2                  0.0
2020-01-01 03:00:00             1.1            10.1                  0.0
2020-01-01 04:00:00             0.3             9.4                  0.0

In [61]:
print(weather.shape)

(35064, 3)

In [63]:
print(weather.isna().sum())

temperature_2m         0
wind_speed_10m         0
shortwave_radiation    0
dtype: int64

In [64]:
weather.describe()

       temperature_2m  wind_speed_10m  shortwave_radiation
count    35064.000000    35064.000000         35064.000000
mean        10.798825       13.608450           130.343058
std          8.091027        6.525289           202.071853
min        -14.900000        0.000000             0.000000
25%          4.600000        8.700000             0.000000
50%         10.200000       12.500000             5.000000
75%         16.800000       17.400000           201.000000
max         37.700000       49.700000           868.000000

### Merging Load and Weather data

In [67]:
df = load.join(weather)
print("===== First 5 ROWS ======")
print(df.head())
print("===== CHECK NAN ======")
print(df.isna().sum())
print("===== CHECK The Shape ======")
print(df.shape)

===== First 5 ROWS ======
                      Load_MW  temperature_2m  wind_speed_10m  \
2020-01-01 00:00:00  43471.87             1.5            11.4
2020-01-01 01:00:00  42401.86             2.0            10.3
2020-01-01 02:00:00  41126.54             1.8            11.2
2020-01-01 03:00:00  40793.28             1.1            10.1
2020-01-01 04:00:00  40710.44             0.3             9.4

                     shortwave_radiation
2020-01-01 00:00:00                  0.0
2020-01-01 01:00:00                  0.0
2020-01-01 02:00:00                  0.0
2020-01-01 03:00:00                  0.0
2020-01-01 04:00:00                  0.0
===== CHECK NAN ======
Load_MW                0
temperature_2m         0
wind_speed_10m         0
shortwave_radiation    0
dtype: int64
===== CHECK The Shape ======
(35064, 4)

In [68]:
df.to_csv("/Users/saif/Desktop/ML_Load_Forecasting/data/Silver/df_clean.csv" )